[package]
name = "clash-verge-self"
version = "2.3.0"
description = "clash verge self"
authors = ["zzzgydi", "wonfen", "MystiPanda", "oomeow"]
license = "GPL-3.0-only"
repository = "https://github.com/oomeow/clash-verge-self.git"
default-run = "clash-verge-self"
edition.workspace = true
build = "build.rs"

[lib]
name = "clash_verge_self_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri-plugin-mihomo.workspace = true
mihomo-rule-parser.workspace = true
process_supervisor.workspace = true
clash-verge-self-utils.workspace = true
clash-verge-self-service.workspace = true

tokio = { workspace = true, features = ["net", "sync", "macros"] }
reqwest.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
anyhow.workspace = true
# log
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
time.workspace = true

# tauri
tauri = { version = "2", features = [
  "protocol-asset",
  "devtools",
  "tray-icon",
  "image-ico",
  "image-png",
] }
tauri-plugin-notification = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2"
rquickjs = "0.11.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-updater = "2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }

warp = { version = "0.4", features = ["server"] }
dunce = "1.0"
nanoid = "0.5"
chrono = {version = "0.4", features = ["serde"] }
sysinfo = "0.39"

delay_timer = "0.11"
auto-launch = "0.6"
percent-encoding = "2.3"
reqwest_dav = "0.3"
zip = "8.0"
sysproxy = { git = "https://github.com/oomeow/sysproxy-rs", branch = "main" }
rust-i18n = "4"
rfd = { version = "0.17", default-features = false, features = [
  "gtk3",
  "common-controls-v6",
] }
network-interface = "2.0.1"

[target.'cfg(windows)'.dependencies]
runas = "=1.2"
deelevate = "0.2"
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(target_os = "linux")'.dependencies]
users = "0.11"
# openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
signal-hook = "0.4"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
verge-dev = []
