// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionType = "HTTP" | "HTTPS" | "Socks4" | "Socks5" | "ShadowSocks" | "Snell" | "Vmess" | "Vless" | "Redir" | "TProxy" | "Trojan" | "Tunnel" | "Tun" | "Tuic" | "Hysteria2" | "AnyTLS" | "Mieru" | "Sudoku" | "TrustTunnel" | "Inner" | "Unknown";
