// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyInfo } from "./ProxyInfo";

/**
 * proxies
 */
export type Proxies = { proxies: { [key in string]: ProxyInfo }, };
