// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";
import type { Proxy } from "./Proxy";
import type { SubscriptionInfo } from "./SubscriptionInfo";
import type { VehicleType } from "./VehicleType";

export type ProxyProvider = { name: string, type: ProviderType, vehicleType: VehicleType, proxies: Array<Proxy>, testUrl: string, expectedStatus: string, updatedAt: string | null, subscriptionInfo: SubscriptionInfo | null, };
