// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleInfo } from "./RuleInfo";

/**
 * rules
 */
export type Rules = { rules: Array<RuleInfo>, };
