// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  /**
   * get the system proxy
   */
  async getSysProxy(): Promise<Result<unknown, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_sys_proxy") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getDefaultBypass(): Promise<Result<string, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_default_bypass") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * get the system proxy
   */
  async getAutoProxy(): Promise<Result<unknown, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_auto_proxy") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getAppDir(): Promise<Result<string, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_app_dir") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async openAppDir(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("open_app_dir") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async openLogsDir(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("open_logs_dir") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async openWebUrl(url: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("open_web_url", { url }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async openCoreDir(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("open_core_dir") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async isPortableVersion(): Promise<Result<boolean, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("is_portable_version") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async isWayland(): Promise<Result<boolean, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("is_wayland") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * restart the sidecar
   */
  async restartSidecar(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("restart_sidecar") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async grantPermissions(core: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("grant_permissions", { core }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async checkPermissionsGranted(
    core: string,
  ): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("check_permissions_granted", { core }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async refreshPermissionsGranted(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("refresh_permissions_granted"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async invokeUwpTool(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("invoke_uwp_tool") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async checkPortAvailable(port: number): Promise<Result<boolean, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("check_port_available", { port }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async copyIconFile(
    path: string,
    name: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("copy_icon_file", { path, name }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async copyClashEnv(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("copy_clash_env") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async downloadIconCache(
    url: string,
    name: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("download_icon_cache", { url, name }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async openDevtools(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("open_devtools") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async setTrayVisible(visible: boolean): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("set_tray_visible", { visible }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getNetInfo(): Promise<Result<NetInfo[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_net_info") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async restartApp(): Promise<void> {
    await TAURI_INVOKE("restart_app");
  },
  async exitApp(): Promise<void> {
    await TAURI_INVOKE("exit_app");
  },
  async getClashInfo(): Promise<Result<ClashInfo, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_clash_info") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getClashLogs(): Promise<Result<string[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_clash_logs") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async patchClashConfig(payload: unknown): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("patch_clash_config", { payload }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async changeClashCore(
    clashCore: string | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("change_clash_core", { clashCore }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getRuntimeConfig(): Promise<Result<unknown | null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_runtime_config") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getRuntimeYaml(): Promise<Result<string, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_runtime_yaml") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getRuntimeLogs(): Promise<
    Result<Partial<{ [key in string]: LogMessage[] }>, string>
  > {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_runtime_logs") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getPreMergeResult(
    parentUid: string | null,
    modifiedUid: string,
  ): Promise<Result<CmdMergeResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_pre_merge_result", {
          parentUid,
          modifiedUid,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async testMergeChain(
    profileUid: string | null,
    modifiedUid: string,
    content: string,
  ): Promise<Result<CmdMergeResult, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("test_merge_chain", {
          profileUid,
          modifiedUid,
          content,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getRuleProviderPayload(
    providerName: string,
    behavior: RuleBehavior,
    format: RuleFormat,
  ): Promise<Result<RulePayload, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_rule_provider_payload", {
          providerName,
          behavior,
          format,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getVergeConfig(): Promise<Result<IVerge, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_verge_config") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async patchVergeConfig(payload: IVerge): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("patch_verge_config", { payload }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async testDelay(url: string): Promise<Result<number, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("test_delay", { url }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getProfiles(): Promise<Result<IProfiles, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_profiles") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getProfile(uid: string): Promise<Result<PrfItem, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_profile", { uid }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getChains(
    profileUid: string | null,
  ): Promise<Result<ChainItem[], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_chains", { profileUid }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getTemplate(
    scope: string,
    language: string,
  ): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("get_template", { scope, language }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async enhanceProfiles(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("enhance_profiles") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * 修改整个 profiles
   */
  async patchProfilesConfig(
    profiles: IProfiles,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("patch_profiles_config", { profiles }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async viewProfile(index: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("view_profile", { index }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  /**
   * 修改某个 profile item
   */
  async patchProfile(
    uid: string,
    profile: PrfItem,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("patch_profile", { uid, profile }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createProfile(
    item: PrfItem,
    fileData: string | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_profile", { item, fileData }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async importProfile(
    url: string,
    option: PrfOption | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("import_profile", { url, option }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async reorderProfile(
    activeId: string,
    overId: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("reorder_profile", { activeId, overId }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async updateProfile(
    uid: string,
    option: PrfOption | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("update_profile", { uid, option }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async deleteProfile(uid: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("delete_profile", { uid }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async readProfileFile(index: string): Promise<Result<string, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("read_profile_file", { index }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async saveProfileFile(
    uid: string,
    fileData: string | null,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("save_profile_file", { uid, fileData }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async checkService(): Promise<
    Result<ServiceJsonResponse<ServiceClashRunInfo>, string>
  > {
    try {
      return { status: "ok", data: await TAURI_INVOKE("check_service") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async installService(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("install_service") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async uninstallService(): Promise<Result<null, string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("uninstall_service") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createLocalBackup(
    onlyBackupProfiles: boolean,
  ): Promise<Result<[string, string], string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_local_backup", { onlyBackupProfiles }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async applyLocalBackup(filePath: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("apply_local_backup", { filePath }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async updateWebdavInfo(
    url: string,
    username: string,
    password: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("update_webdav_info", {
          url,
          username,
          password,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async createAndUploadBackup(
    onlyBackupProfiles: boolean,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("create_and_upload_backup", {
          onlyBackupProfiles,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listBackup(): Promise<Result<BackupListFile[], string>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_backup") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async downloadBackupAndReload(
    fileName: string,
  ): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("download_backup_and_reload", { fileName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async deleteBackup(fileName: string): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("delete_backup", { fileName }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type BackupListFile = {
  href: string;
  last_modified: string;
  content_length: number;
  content_type: string;
  tag: string | null;
};
export type ChainItem = {
  uid: string;
  name: string;
  desc: string;
  file: string;
  type: ChainType;
  parent: string | null;
  enable: boolean;
  scope: ScopeType;
};
export type ChainType = "merge" | "script";
export type ClashInfo = {
  /**
   * clash core mode
   */
  mode: string;
  /**
   * clash core port
   */
  mixed_port: number;
  port: number;
  socks_port: number;
  redir_port: number;
  /**
   * same as `external-controller`
   */
  server: string;
  /**
   * clash secret
   */
  secret: string | null;
  cors: Cors;
};
export type CmdMergeResult = {
  config: string;
  logs: Partial<{ [key in string]: LogMessage[] }>;
};
export type Cors = { allow_private_network: boolean; allow_origins: string[] };
/**
 * Define the `profiles.yaml` schema
 */
export type IProfiles = {
  /**
   * same as PrfConfig.current
   */
  current: string | null;
  /**
   * same as PrfConfig.chain
   */
  chain: string[] | null;
  /**
   * profile list
   */
  items: PrfItem[] | null;
};
/**
 * ### `verge.yaml` schema
 */
export type IVerge = {
  /**
   * app listening port for app singleton
   */
  app_singleton_port: number | null;
  /**
   * app log level
   * silent | error | warn | info | debug | trace
   */
  app_log_level: string | null;
  language: string | null;
  /**
   * `light` or `dark` or `system`
   */
  theme_mode: string | null;
  /**
   * tray click event
   */
  tray_event: string | null;
  /**
   * copy env type
   */
  env_type: string | null;
  /**
   * start page
   */
  start_page: string | null;
  /**
   * startup script path
   */
  startup_script: string | null;
  /**
   * enable traffic graph default is true
   */
  traffic_graph: boolean | null;
  /**
   * show memory info (only for Mihomo)
   */
  enable_memory_usage: boolean | null;
  /**
   * enable group icon
   */
  enable_group_icon: boolean | null;
  /**
   * common tray icon
   */
  common_tray_icon: boolean | null;
  /**
   * tray icon
   */
  tray_icon: string | null;
  /**
   * menu icon
   */
  menu_icon: string | null;
  /**
   * sysproxy tray icon
   */
  sysproxy_tray_icon: boolean | null;
  /**
   * tun tray icon
   */
  tun_tray_icon: boolean | null;
  /**
   * windows service mode
   */
  enable_service_mode?: boolean | null;
  /**
   * can the app auto startup
   */
  enable_auto_launch: boolean | null;
  /**
   * 是否启用系统标题栏
   */
  enable_system_title_bar: boolean | null;
  /**
   * 是否保持UI界面活动
   */
  enable_keep_ui_active: boolean | null;
  /**
   * not show the window on launch
   *
   * TODO: __即将弃用__
   */
  enable_silent_start: boolean | null;
  silent_start_mode: SilentStartMode | null;
  /**
   * set system proxy
   */
  enable_system_proxy: boolean | null;
  /**
   * enable proxy guard
   */
  enable_proxy_guard: boolean | null;
  /**
   * set system proxy bypass
   *
   * TODO: __即将弃用__
   */
  system_proxy_bypass: string | null;
  /**
   * system proxy bypass for windows
   */
  windows_bypass: string | null;
  /**
   * system proxy bypass for macos
   */
  macos_bypass: string | null;
  /**
   * system proxy bypass for linux
   */
  linux_bypass: string | null;
  /**
   * proxy guard duration
   */
  proxy_guard_duration: number | null;
  /**
   * use pac mode
   */
  proxy_auto_config: boolean | null;
  /**
   * pac script content
   */
  pac_file_content: string | null;
  /**
   * light theme setting
   */
  light_theme_setting: IVergeTheme | null;
  /**
   * dark theme setting
   */
  dark_theme_setting: IVergeTheme | null;
  /**
   * web ui list
   */
  web_ui_list: string[] | null;
  /**
   * clash core path
   */
  clash_core?: string | null;
  /**
   * hotkey map
   * format: {func},{key}
   */
  hotkeys: string[] | null;
  /**
   * 切换代理时自动关闭连接
   */
  auto_close_connection: boolean | null;
  /**
   * 是否自动检查更新
   */
  auto_check_update: boolean | null;
  /**
   * 默认的延迟测试连接
   */
  default_latency_test: string | null;
  /**
   * 默认的延迟测试超时时间
   */
  default_latency_timeout: number | null;
  /**
   * proxy 页面布局 列数
   */
  proxy_layout_column: number | null;
  /**
   * 测试网站列表
   */
  test_list: IVergeTestItem[] | null;
  /**
   * 日志清理
   * 0: 不清理; 1: 7天; 2: 30天; 3: 90天
   */
  auto_log_clean: number | null;
  /**
   * window size and position
   */
  window_size_position?: number[] | null;
  /**
   * window size and position
   */
  window_is_maximized?: boolean | null;
  /**
   * 是否启用随机端口
   */
  enable_random_port: boolean | null;
  /**
   * webdav url
   */
  webdav_url: string | null;
  /**
   * webdav username
   */
  webdav_username: string | null;
  /**
   * webdav password
   */
  webdav_password: string | null;
  /**
   * enable tray
   */
  enable_tray: boolean | null;
  /**
   * keep in dock
   */
  keep_in_dock: boolean | null;
  /**
   * enable external controller, such as 127.0.0.1:8080
   */
  enable_external_controller: boolean | null;
};
export type IVergeTestItem = {
  uid: string | null;
  name: string | null;
  icon: string | null;
  url: string | null;
};
export type IVergeTheme = {
  primary_color: string | null;
  secondary_color: string | null;
  primary_text: string | null;
  secondary_text: string | null;
  info_color: string | null;
  error_color: string | null;
  warning_color: string | null;
  success_color: string | null;
  font_family: string | null;
  css_injection: string | null;
};
export type LogMessage = {
  method: string;
  data: string[];
  exception: string | null;
};
export type NetInfo = {
  name: string;
  ipv4: string | null;
  ipv6: string | null;
};
export type PrfExtra = {
  upload: number;
  download: number;
  total: number;
  expire: number;
};
export type PrfItem = {
  uid: string | null;
  /**
   * profile item type
   * enum value: remote | local | script | merge
   */
  type: ProfileType | null;
  /**
   * profile name
   */
  name: string | null;
  /**
   * profile description
   */
  desc?: string | null;
  /**
   * profile file
   */
  file: string | null;
  /**
   * this chain is belong to profile
   */
  parent?: string | null;
  /**
   * enable chain
   */
  enable?: boolean | null;
  /**
   * scope of chain  (GLOBAL / SPECIFIC)
   */
  scope?: ScopeType | null;
  /**
   * selected information
   */
  selected?: PrfSelected[] | null;
  /**
   * profile rule providers path
   */
  rule_providers_path?: Partial<{ [key in string]: string }> | null;
  chain?: string[] | null;
  /**
   * source url
   */
  url?: string | null;
  /**
   * subscription user info
   */
  extra?: PrfExtra | null;
  /**
   * some options of the item
   */
  option?: PrfOption | null;
  /**
   * profile web page url
   */
  home?: string | null;
  /**
   * updated time
   */
  updated: number | null;
};
export type PrfOption = {
  /**
   * for `remote` profile's http request
   * see issue #13
   */
  user_agent?: string | null;
  /**
   * for `remote` profile
   * use system proxy
   */
  with_proxy?: boolean | null;
  /**
   * for `remote` profile
   * use self proxy
   */
  self_proxy?: boolean | null;
  update_interval?: number | null;
  /**
   * for `remote` profile
   * disable certificate validation
   * default is `false`
   */
  danger_accept_invalid_certs?: boolean | null;
};
export type PrfSelected = { name: string | null; now: string | null };
export type ProfileType = "local" | "remote" | "merge" | "script";
export type RuleBehavior = "Domain" | "IPCIDR" | "Classical";
export type RuleFormat = "YamlRule" | "TextRule" | "MrsRule";
export type RulePayload = { count: number; rules: string[] };
export type ScopeType = "global" | "specific";
export type ServiceClashRunInfo = {
  info: ServiceStartBody | null;
  is_running: boolean;
  pid: number | null;
  restart_count: number;
};
export type ServiceJsonResponse<T> = {
  code: number;
  msg: string;
  data: T | null;
};
export type ServiceStartBody = {
  core_type: string | null;
  socket_path: string | null;
  bin_path: string;
  config_dir: string;
  config_file: string;
  log_file: string;
};
export type SilentStartMode = "bootup" | "global" | "off";

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
