name: Alpha Build

on:
  push:
    branches:
      - dev
    tags-ignore:
      - updater
      - alpha
      - "v*"
  workflow_dispatch:

concurrency:
  group: alpha-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  build-dist-js:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check mihomo changed
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            mihomo:
              - 'crates/tauri-plugin-mihomo/guest-js/**'
              - 'crates/tauri-plugin-mihomo/src/models.rs'

      - name: install webkit2gtk
        if: steps.filter.outputs.mihomo == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev

      - name: Install Rust Stable
        if: steps.filter.outputs.mihomo == 'true'
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Rust Cache
        if: steps.filter.outputs.mihomo == 'true'
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Node
        if: steps.filter.outputs.mihomo == 'true'
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - name: Install pnpm
        if: steps.filter.outputs.mihomo == 'true'
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        with:
          run_install: false

      - name: Build mihomo api
        if: steps.filter.outputs.mihomo == 'true'
        run: |
          pnpm i
          pnpm build:mihomo-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check file changed
        if: steps.filter.outputs.mihomo == 'true'
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          base: HEAD
          filters: |
            frontend:
              - 'crates/tauri-plugin-mihomo/dist-js/**'
              - 'crates/tauri-plugin-mihomo/guest-js/**'

      - name: Update dist-js or guest-js
        if: steps.filter.outputs.mihomo == 'true' && steps.changes.outputs.frontend == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add crates/tauri-plugin-mihomo/dist-js crates/tauri-plugin-mihomo/guest-js
          git commit -m "chore: update tauri-plugin-mihomo frontend code"
          git push origin dev

  delete-release-assets:
    needs: [build-dist-js]
    runs-on: ubuntu-latest
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: alpha
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: |
            *.rpm
            *.deb
            *.zst
            *.dmg
            *.exe
            *.gz
            *.sig
            *.zip
            *.json

  alpha:
    needs: [delete-release-assets]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: dev

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check ${{ matrix.target }} --alpha --no-confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tauri build
        uses: tauri-apps/tauri-action@84b9d35b5fc46c1e45415bdb6144030364f7ebc5 # v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          CLASH_VERGE_SELF_SERVICE_PSK: ${{secrets.CLASH_VERGE_SELF_SERVICE_PSK}}
        with:
          tagName: alpha
          releaseName: "Clash Verge Self Alpha"
          releaseBody: "More new features are now supported."
          releaseDraft: false
          prerelease: true
          tauriScript: pnpm
          args: --target ${{ matrix.target }}

      - name: Portable Bundle
        if: matrix.os == 'windows-latest'
        run: pnpm portable ${{ matrix.target }} --alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  alpha-for-linux:
    needs: [delete-release-assets]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: i686-unknown-linux-gnu
          - os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04
            target: armv7-unknown-linux-gnueabihf
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: dev

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Binstall
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        uses: cargo-bins/cargo-binstall@145ab7536465bbe738da5f500d3d211eadd3f655 # main

      - name: Install Cross
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        run: cargo binstall -y cross

      - name: Install Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        name: Install pnpm
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check ${{ matrix.target }} --alpha --no-confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tauri build (x86_64)
        if: startsWith(matrix.target, 'x86_64')
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          CLASH_VERGE_SELF_SERVICE_PSK: ${{secrets.CLASH_VERGE_SELF_SERVICE_PSK}}
        run: |
          pnpm build --target ${{ matrix.target }}

      - name: Tauri build (other)
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          CLASH_VERGE_SELF_SERVICE_PSK: ${{secrets.CLASH_VERGE_SELF_SERVICE_PSK}}
        run: |
          pnpm build -r cross --target ${{ matrix.target }} -b deb,rpm

      - name: Portable Bundle (Linux)
        run: pnpm portable ${{ matrix.target }} --alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build for Linux
      #   uses: ./.github/build-for-linux
      #   env:
      #     TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      #     TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      #   with:
      #     target: ${{ matrix.target }}
      #     alpha: true

      - name: Get Version
        id: get_version
        run: |
          sudo apt-get update
          sudo apt-get install jq
          echo "VERSION=$(cat package.json | jq '.version' | tr -d '"')" >> "$GITHUB_OUTPUT"

      # - name: Upload Release
      #   if: startsWith(matrix.target, 'x86_64')
      #   uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
      #   with:
      #     tag_name: alpha
      #     name: "Clash Verge Self Alpha"
      #     prerelease: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     files: target/${{ matrix.target }}/release/bundle/appimage/*.AppImage*

      - name: Upload Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          tag_name: alpha
          name: "Clash Verge Self Alpha"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            target/${{ matrix.target }}/release/bundle/deb/*.deb
            target/${{ matrix.target }}/release/bundle/rpm/*.rpm

  pkgbuild:
    name: PKGBUILD for ArchLinux
    needs: [alpha-for-linux]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: dev

      - name: Update Checksums
        run: |
          echo "version: ${{ needs.alpha-for-linux.outputs.VERSION }}"
          wget https://github.com/oomeow/clash-verge-self/releases/download/alpha/clash-verge-self_${{ needs.alpha-for-linux.outputs.VERSION }}_amd64.deb -O amd64.deb
          sed -i "s/sha256sums_x86_64=.*/sha256sums_x86_64=(\"$(sha256sum ./amd64.deb | awk '{print $1}')\")/" archbuild/alpha/PKGBUILD

      - name: Makepkg Build and Check
        id: makepkg
        uses: CachyOS/pkgbuild-action@99a0608d129dae363a6174971400e018dd0f4577 # master
        with:
          pkgdir: archbuild/alpha

      - name: Print Package Files
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"

      - name: Upload Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          tag_name: alpha
          name: "Clash Verge Self Alpha"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.makepkg.outputs.pkgfile0 }}

  update_tag:
    name: Update tag
    runs-on: ubuntu-22.04
    needs: [alpha, pkgbuild]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: dev

      - name: Set Env
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
        shell: bash

      - name: Update Tag
        uses: richardsimko/update-tag@aab2434e9a5040687874aa39d1c6377ec0cb0d94 # v1
        with:
          tag_name: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          tag_name: alpha
          name: "Clash Verge Self Alpha"
          body_path: ${{ github.workspace }}/CHANGELOG.md
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: false
