name: Build dist-js

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev
  #   paths:
  #     - "crates/tauri-plugin-mihomo/guest-js/**"
  #     - "crates/tauri-plugin-mihomo/src/models.rs"

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6
        name: Install pnpm
        with:
          run_install: false

      - name: Build mihomo api
        run: |
          pnpm i
          pnpm build:mihomo-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check file changed
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          base: HEAD
          filters: |
            frontend:
              - 'crates/tauri-plugin-mihomo/dist-js/**'
              - 'crates/tauri-plugin-mihomo/guest-js/**'

      - name: Update dist-js or guest-js
        if: steps.changes.outputs.frontend == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add crates/tauri-plugin-mihomo/dist-js crates/tauri-plugin-mihomo/guest-js
          git commit -m "chore: update tauri-plugin-mihomo frontend code"
          git push origin dev
