name: PR Check

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Check file changed
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: changes
        with:
          filters: |
            frontend:
              - 'src/**'
              - '**/package.json'
              - '**/pnpm-lock.yaml'
            backend:
              - 'src-tauri/**'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
            bundle:
              - 'cross_dockerfile/**'
              - 'src-tauri/template/**'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Install Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24"

      - name: Install pnpm + deps
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check --alpha --no-confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # frontend lint
      - name: frontend lint
        run: pnpm lint

      # frontend build (always build)
      - name: frontend build
        run: pnpm web:build

      # rust clippy
      - name: Rust clippy
        if: steps.changes.outputs.backend == 'true'
        run: |
          cd src-tauri
          cargo clippy

      - name: Build Tauri
        if: steps.changes.outputs.bundle == 'true'
        run: pnpm build -c ./src-tauri/tauri.conf-pr.json
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
