name: PR Check

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check file changed
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            frontend:
              - 'src/**'
              - '**/package.json'
              - '**/pnpm-lock.yaml'
            backend:
              - 'src-tauri/**'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
            bundle:
              - 'cross_dockerfile/**'
              - 'src-tauri/template/**'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"

      - name: Install pnpm + deps
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check --alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # frontend lint
      - name: frontend lint
        run: pnpm lint

      # frontend build (always build)
      - name: frontend build
        run: pnpm web:build

      # rust clippy
      - name: Rust clippy
        if: steps.changes.outputs.backend == 'true'
        run: |
          cd src-tauri
          cargo clippy

      # bundle build
      - name: Overwrite Tauri config
        if: steps.changes.outputs.bundle == 'true'
        run: |
          cp ./src-tauri/tauri.conf.pr.json ./src-tauri/tauri.conf.json

      - name: Build Tauri
        if: steps.changes.outputs.bundle == 'true'
        run: pnpm build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
