name: Pre-Release Service CI

on:
  # push:
  #   branches: [feat/service]
  #   paths:
  #     - crates/clash-verge-self-service/**
  #     - .github/workflows/service-alpha.yml
  workflow_dispatch:

concurrency:
  group: service-alpha-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  pre-release-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check Service changed
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            service:
              - 'crates/clash-verge-self-service/**'

      - name: Install Rust
        if: matrix.os != 'ubuntu-latest' && steps.filter.outputs.service == 'true'
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Add Rust Target
        if: matrix.os != 'ubuntu-latest' && steps.filter.outputs.service == 'true'
        run: rustup target add ${{ matrix.target }}

      - name: Build (Windows / MacOS)
        if: matrix.os != 'ubuntu-latest' && steps.filter.outputs.service == 'true'
        env:
          CLASH_VERGE_SELF_SERVICE_PSK: ${{secrets.CLASH_VERGE_SELF_SERVICE_PSK}}
        run: cargo build --package clash-verge-self-service --release --target ${{ matrix.target }}

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest' && steps.filter.outputs.service == 'true'
        uses: ./.github/build-service-for-linux
        env:
          CLASH_VERGE_SELF_SERVICE_PSK: ${{secrets.CLASH_VERGE_SELF_SERVICE_PSK}}
        with:
          target: ${{ matrix.target }}

      - name: Rename Clash Verge Service (Linux / MacOS)
        if: matrix.os != 'windows-latest' && steps.filter.outputs.service == 'true'
        run: |
          cp target/${{ matrix.target }}/release/clash-verge-self-service ./clash-verge-self-service-${{ matrix.target }}

      - name: Rename Clash Verge Service (Windows)
        if: matrix.os == 'windows-latest' && steps.filter.outputs.service == 'true'
        run: |
          cp target/${{ matrix.target }}/release/clash-verge-self-service.exe ./clash-verge-self-service-${{ matrix.target }}.exe

      - name: Create Pre-Release
        if: steps.filter.outputs.service == 'true'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          name: Clash Verge Self Service Alpha
          tag_name: service-alpha
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./clash-verge-self-service-${{ matrix.target }}
            ./clash-verge-self-service-${{ matrix.target }}.exe
